image: 
  name: javh/immcantation:test-r

pipelines:
  default:
    - step:
        script:
          - sed -i '/test/ d' .Rbuildignore
          - Rscript tests/setup/install_alakazam.R
          - R CMD build .
          - R CMD check *.tar.gz --as-cran --run-donttest --timings


