image: 
  name: ssnn/immcantation
  username: $USERNAME
  password: $PASSWORD
  email: $EMAIL

pipelines:
  default:
    - step:
        script:
          - Rscript -e 'library(devtools); install_bitbucket("kleinstein/alakazam@default")'
          - R CMD build .
          - R CMD check *.tar.gz


