site_name: shazam
site_favicon: img/favicon.ico
repo_url: https://bitbucket.org/kleinstein/shazam
edit_uri: src/master/docs/
theme: readthedocs
markdown_extensions:
  - def_list
  - sane_lists
  - smarty
  - toc:
      permalink: True
docs_dir: docs
pages:
  - 'About':
    - 'Introduction': index.md
    - 'Download & Installation': install.md
    - 'Package Overview': topics/shazam.md
    - 'Release Notes': news.md
    - 'Related Projects': projects.md
  - 'Vignettes':
    - 'Basic mutational load analysis': vignettes/Mutation-Vignette.md
    - 'Quantification of selection pressure': vignettes/Baseline-Vignette.md
    - 'Tuning clonal assignment thresholds with nearest neighbor distances': vignettes/DistToNearest-Vignette.md
    - 'Inferring SHM targeting models': vignettes/Targeting-Vignette.md
    - 'Simulation based on a targeting model': vignettes/Shmulate-Vignette.md
  - 'Help Topics':
    - 'Mutation Profiling':
      - topics/collapseClones.md
      - topics/consensusSequence.md
      - topics/expectedMutations.md
      - topics/observedMutations.md
      - topics/calcExpectedMutations.md
      - topics/calcObservedMutations.md
      - topics/slideWindowDb.md
      - topics/slideWindowSeq.md
      - topics/slideWindowTune.md
      - topics/slideWindowTunePlot.md
      - topics/shmulateSeq.md
      - topics/shmulateTree.md
    - 'Targeting Inference':
      - topics/calculateMutability.md
      - topics/createMutabilityMatrix.md
      - topics/createSubstitutionMatrix.md
      - topics/extendMutabilityMatrix.md
      - topics/extendSubstitutionMatrix.md
      - topics/createTargetingMatrix.md
      - topics/createTargetingModel.md
      - topics/makeAverage1merMut.md
      - topics/makeAverage1merSub.md
      - topics/makeDegenerate5merMut.md
      - topics/makeDegenerate5merSub.md
      - topics/minNumMutationsTune.md
      - topics/minNumSeqMutationsTune.md
      - topics/plotMutability.md
      - topics/plotTune.md
      - topics/MutabilityModel-class.md
      - topics/TargetingMatrix-class.md
      - topics/TargetingModel-class.md
    - 'Empirical Models':
      - topics/HH_S1F.md
      - topics/HH_S5F.md
      - topics/HKL_S1F.md
      - topics/HKL_S5F.md
      - topics/MK_RS1NF.md
      - topics/MK_RS5NF.md
      - topics/U5N.md
    - 'Selection Analysis':
      - topics/calcBaseline.md
      - topics/groupBaseline.md
      - topics/summarizeBaseline.md
      - topics/testBaseline.md
      - topics/plotBaselineDensity.md
      - topics/plotBaselineSummary.md
      - topics/createBaseline.md
      - topics/editBaseline.md
      - topics/Baseline-class.md
    - 'Distance Profiling':
      - topics/distToNearest.md
      - topics/findThreshold.md
      - topics/plotDensityThreshold.md
      - topics/plotGmmThreshold.md
      - topics/calcTargetingDistance.md
      - topics/writeTargetingDistance.md
      - topics/DensityThreshold-class.md
      - topics/GmmThreshold-class.md
    - 'Mutation & Region Definitions':
      - topics/MUTATION_SCHEMES.md
      - topics/IMGT_SCHEMES.md
      - topics/createMutationDefinition.md
      - topics/createRegionDefinition.md
      - topics/MutationDefinition-class.md
      - topics/RegionDefinition-class.md
