name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  unittest:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    container:
      image: immcantation/test:devel
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          Rscript tests/setup/install_dep.R
      - name: Document
        run: |
          devtools::document()
        shell: Rscript {0}
      - name: Update buildignore
        run: |
            sed -i '/test/ d' .Rbuildignore
        shell: bash
      - name: Run Tests
        run: |
            testthat::test_local()
        shell: Rscript {0}
      - name: Check usage
        run: |
          devtools::install()
          pkg_name <- read.dcf("DESCRIPTION")[1, "Package"]
          library(pkg_name, character.only=T)
          usage_out <- capture.output(codetools::checkUsagePackage(pack=pkg_name))
          if (length(usage_out) > 0) {
            print(usage_out)
            warning("Found issues with code usage.")
          }
        shell: Rscript {0}  
      - name: CRAN check
        env:
          _R_CHECK_CRAN_INCOMING_: false
        run: |
              options(crayon.enabled=TRUE)
              rcmdcheck::rcmdcheck(
                args = c("--no-manual", 
                          "--no-tests", 
                          "--as-cran", 
                          "--run-donttest", 
                          "--timings"),
                error_on = "warning", 
                check_dir = "check"
              )
        shell: Rscript {0}
      # - name: Build docs
      #   run: |
      #      git rm -r docs/topics docs/vignettes
      #      Rscript docs/build.R
      #      CHANGES=$(git status --porcelain | wc -l)
      #         if [[ "${CHANGES}" -gt 0 ]]; then
      #           git add docs/*
      #           git commit --allow-empty -m "[skip ci] Auto-build docs."
      #           git push
      #         fi
      - name: Update container
        run: |
          curl -H "Content-Type:application/json" --data '{"docker_tag":"devel"}' -X POST https://hub.docker.com/api/build/v1/source/${{ secrets.DOCKERHUB_REPO }}/trigger/${{ secrets.DOCKERHUB_TRIGGER }}/call/
          